// frontend/rectrace/src/app/custom-interactions/components/renderers/app-id-cell-renderer.component.ts
import { Component } from '@angular/core';
import { ICellRendererAngularComp } from 'ag-grid-angular';
import { ICellRendererParams } from 'ag-grid-community';

@Component({
  selector: 'app-app-id-cell-renderer',
  template: `
    @if (appId) {
    <a
       [href]="getFileUrl()"
       target="_blank"
       class="file-link"
       [matTooltip]="getTooltipText()">
      {{ appId }}
    </a>
    } @else {
    <span>{{ appId }}</span>
    }
  `,
  styles: [`
    .file-link {
      color: var(--google-blue, #1a73e8);
      text-decoration: underline;
      cursor: pointer;
    }
    .file-link:hover {
      text-decoration: none;
    }
  `]
})
export class AppIDCellRendererComponent implements ICellRendererAngularComp {
  appId: string = '';
  appName: string = '';

  agInit(params: ICellRendererParams): void {
    this.appId = params.value;
    this.appName = params.data?.app_name || "";
  }

  refresh(params: ICellRendererParams): boolean {
    return false;
  }

  getFileUrl(): string {
    return "https://lnkd.in/gpAtSBRj";
  }

  getTooltipText(): string {
    return `View details of ${this.appName}`;
  }

  destroy(): void {
    // Cleanup if needed
  }
}

// frontend-react/src/search/renderers/AppIDCellRenderer.tsx
import type { ICellRendererParams } from 'ag-grid-community'

/**
 * AppIDCellRenderer — React port of AppIDCellRendererComponent.
 *
 * Behavioral parity with Angular source:
 *   frontend/rectrace/src/app/custom-interactions/components/renderers/app-id-cell-renderer.component.ts
 *
 * - Truthy params.value → <a href="https://lnkd.in/gpAtSBRj"> opening in a new tab.
 *   title attribute = "View details of {params.data.app_name}".
 * - Falsy params.value → plain <span>{value}</span> (no link).
 *
 * Styling uses the Phase 2 design tokens (text-primary, underline) — no raw hex.
 */
export function AppIDCellRenderer(params: ICellRendererParams) {
  const value = params.value as string | undefined | null
  const data = params.data as Record<string, unknown> | undefined
  const appName = (data?.app_name as string | undefined) ?? ''
  if (!value) {
    return <span>{value}</span>
  }
  return (
    <a
      href="https://lnkd.in/gpAtSBRj"
      target="_blank"
      rel="noopener noreferrer"
      title={`View details of ${appName}`}
      className="text-primary underline hover:no-underline"
    >
      {value}
    </a>
  )
}
